# Generated by Django 4.2.5 on 2023-10-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testdjango',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userlist',
            options={'managed': False},
        ),
    ]
